config/routes.rb
######API#######
require 'api_constraints'

Rails.application.routes.draw do


  resources :colours

  get 'explorer/tree_view'
  get 'explorer/add_column'

  # API
  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do
      resources :projects do
        resources :tasks, only: [:index,:update,:show] do
          get 'all', on: :collection
          put 'update_gantt', on: :member, action:'update_gantt'
          delete 'update_gantt', on: :member, action:'destroy'
          post 'update_gantt', on: :collection, action:'create'
          resources :comments, only: [:create]
        end

        resources :indicators do
        end

        get 'all', on: :collection
      end

      #Métodos para usuarios
      post 'users/login', to: 'users#login'
      delete 'users/logout', to: 'users#logout'

      #Métodos de progresos
      get '/progress/estimated_in_resources_by_week' 
      get '/progress/real_in_resources_by_week' 
      get '/progress/estimated_in_days_by_week'
      get '/progress/real_in_days_by_week' 
      get '/progress/all_progress'

      get '/progress/performance_in_resources_by_week'
      get '/progress/performance_in_one_by_week'
      post '/push/send_token'

      
      get '/progress/performance_estimated_by_week'
      get '/progress/performance_real_by_week'

    end
  end

#######termino API#####
  
  # Página de errores
  get 'errors/file_not_found'
  get 'errors/unprocessable'
  get 'errors/internal_server_error'
  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all


  #usuarios con gema devise
  devise_for :users


  #Resources genera todas las rutas CRUD para cada uno de estos objetos
  resources :projects do
    get 'delete'
    get 'second_indicators'
    get 'tree_view'
    get 'root'
    get 'second_root'
    get 'stads'
    get 'add_tree_view_column'
    get 'export'
    get 'kanban_board', to: 'kanban_board#index', as: :kanban_board_index
    get 'gantt', to: 'gantt#index'

    resources :indicators
    resources :users, only: [:index]
    resources :tasks do
      resources :reports
      resources :comments

    end
  end

  resources :tasks do
    get 'delete_confirmation'
    get 'fast_report'
    get 'toggle_urgent'
    get 'change_colour'
    post 'move_dates'
  end
  get 'update_tree_view', to: 'tasks#update_tree_view'

  get 'gantt', to: 'gantt#index'
  get 'explorer', to: 'explorer#tree_view'

  resources :comments
  resources :reports
  resources :assignments
  resources :users

  resources :indicators

  resources :enterprises do
    resources :projects
    resources :users
  end

  namespace :kanban_board do
    get 'index'
    get 'update_item_partial'
  end




  root 'explorer#tree_view'
end

app/controllers/resources_reports_controller.rb
class ResourcesReportsController < ApplicationController
  before_action :set_resources_report, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @resources_reports = ResourcesReport.all

  end

  def show

  end

  def new
    @resources_report = ResourcesReport.new
  end

  def edit
  end

  def create
    @resources_report = ResourcesReport.new(resources_report_params)

    respond_to do |format|

      if @resources_report.save
        format.html { redirect_to @resources_report }
        format.json { render :show, status: :created, location: @resources_report }
      else
        format.html { render :new }
        format.json { render json: @resources_report.errors, status: :unprocessable_entity }
      end
    end

  end

  def update

    respond_to do |format|
      if @resources_report.update(resources_report_params)
        format.html { redirect_to @resources_report }
      else
        format.html { render :edit }
        format.json { render json: @resources_report.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @resources_report.destroy
    respond_with(@resources_report)
  end

  private
  def set_resources_report
    @resources_report = ResourcesReport.find(params[:id])
  end

  def resources_report_params
    params.require(:resources_report).permit(:task_id, :resources, :user_id)
  end
end

app/helpers/resources_reports_helper.rb
module ResourcesReportsHelper
end

app/views/resources_reports/_form.html.erb
<%= form_for(@resources_report) do |f| %>
  <% if @resources_report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resources_report.errors.count, "error") %> prohibited this resources_report from being saved:</h2>

      <ul>
      <% @resources_report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :task_id %><br>
    <%= f.number_field :task_id %>
  </div>
  <div class="field">
    <%= f.label :resources %><br>
    <%= f.text_field :resources %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resources_reports/edit.html.erb
<h1>Editing resources_report</h1>

<%= render 'form' %>

<%= link_to 'Show', @resources_report %> |
<%= link_to 'Back', resources_reports_path %>

app/views/resources_reports/index.html.erb
<h1>Listing resources_reports</h1>

<table>
  <thead>
    <tr>
      <th>Task</th>
      <th>Resources</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @resources_reports.each do |resources_report| %>
      <tr>
        <td><%= resources_report.task_id %></td>
        <td><%= resources_report.resources %></td>
        <td><%= resources_report.user_id %></td>
        <td><%= link_to 'Show', resources_report %></td>
        <td><%= link_to 'Edit', edit_resources_report_path(resources_report) %></td>
        <td><%= link_to 'Destroy', resources_report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resources report', new_resources_report_path %>

app/views/resources_reports/new.html.erb
<h1>New resources_report</h1>

<%= render 'form' %>

<%= link_to 'Back', resources_reports_path %>

app/views/resources_reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Task:</strong>
  <%= @resources_report.task_id %>
</p>

<p>
  <strong>Resources:</strong>
  <%= @resources_report.resources %>
</p>

<p>
  <strong>User:</strong>
  <%= @resources_report.user_id %>
</p>

<%= link_to 'Edit', edit_resources_report_path(@resources_report) %> |
<%= link_to 'Back', resources_reports_path %>