config/routes.rb
######API#######
require 'api_constraints'

Rails.application.routes.draw do


  resources :colours

  get 'explorer/tree_view'
  get 'explorer/add_column'

  # API
  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do
      resources :projects do
        resources :tasks, only: [:index,:update,:show] do
          get 'all', on: :collection
          put 'update_gantt', on: :member, action:'update_gantt'
          delete 'update_gantt', on: :member, action:'destroy'
          post 'update_gantt', on: :collection, action:'create'
          resources :comments, only: [:create]
        end

        resources :indicators do
        end

        get 'all', on: :collection
      end

      #Métodos para usuarios
      post 'users/login', to: 'users#login'
      delete 'users/logout', to: 'users#logout'

      #Métodos de progresos
      get '/progress/estimated_in_resources_by_week' 
      get '/progress/real_in_resources_by_week' 
      get '/progress/estimated_in_days_by_week'
      get '/progress/real_in_days_by_week' 
      get '/progress/all_progress'

      get '/progress/performance_in_resources_by_week'
      get '/progress/performance_in_one_by_week'
      post '/push/send_token'

      
      get '/progress/performance_estimated_by_week'
      get '/progress/performance_real_by_week'

    end
  end

#######termino API#####
  
  # Página de errores
  get 'errors/file_not_found'
  get 'errors/unprocessable'
  get 'errors/internal_server_error'
  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all


  #usuarios con gema devise
  devise_for :users


  #Resources genera todas las rutas CRUD para cada uno de estos objetos
  resources :projects do
    get 'delete'
    get 'second_indicators'
    get 'tree_view'
    get 'root'
    get 'second_root'
    get 'stads'
    get 'add_tree_view_column'
    get 'export'
    get 'kanban_board', to: 'kanban_board#index', as: :kanban_board_index
    get 'gantt', to: 'gantt#index'

    resources :indicators
    resources :users, only: [:index]
    resources :tasks do
      resources :reports
      resources :comments

    end
  end

  resources :tasks do
    get 'delete_confirmation'
    get 'fast_report'
    get 'toggle_urgent'
    get 'change_colour'
    post 'move_dates'
  end
  get 'update_tree_view', to: 'tasks#update_tree_view'

  get 'gantt', to: 'gantt#index'
  get 'explorer', to: 'explorer#tree_view'

  resources :comments
  resources :reports
  resources :assignments
  resources :users

  resources :indicators

  resources :enterprises do
    resources :projects
    resources :users
  end

  namespace :kanban_board do
    get 'index'
    get 'update_item_partial'
  end




  root 'explorer#tree_view'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	#Pertenece a una tarea
	belongs_to :task

	# pertenece a un usuario ya que no solo el dueño de la tarea puede dejar comentarios en esta, tambien el 
	# admin del proyecto y el super admin
	belongs_to :user

end

app/controllers/api/v1/comments_controller.rb
#Aquí definimos las respuestas a las llamadas de la api
module Api
  module V1

    class CommentsController < ActionController::Base
      before_filter :restrict_access, only: [:create]
      before_action :set_user, only: [:create]
    #Con esto definimos como queremos entregar la respuesta.
    respond_to 'json'



      def create
      @comment = Comment.new(:task_id => params[:task_id], :user_id => @user.id, :description => params[:description])
        if @comment.save
          render nothing: true, status: :created
        end
      end

      # Para restringir acceso el usuario debe entregar el token
      private
      def restrict_access
        token=request.headers["Authorization"]
          ak = ApiKey.where(access_token: token).first
          if ak
            unless ak.valid_token
              ak.destroy
            end
          end
          ApiKey.exists?(access_token: token)
        end


      def set_user
        token = request.headers["Authorization"]
        @user = ApiKey.find_by_access_token(token).user
      end

    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        @task = @comment.task
        format.html { redirect_to request.referer, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
        format.js 
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @task = @comment.task
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
      format.js 
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params[:comment].permit(:description, :task_id, :user_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comments_list.html.erb
<div class="row history_list">
	<% @task.comments.reverse.each do |comment|%>
		<div class="row item">
			<div class="col-md-2">
				<div class="row">
					<%= comment.user.f_name %>
				</div>
				<div class="row date">
					<%= comment.created_at.strftime("%d %b. %Y") %> - 
					<%= comment.created_at.strftime("%H:%M")%>
				</div>
			</div>
			<div class="col-md-9">
				<%= comment.description %>
			</div>
			<div class="col-md-1">
				<%= link_to 'x', comment_path(comment), method: :delete, data: { confirm: '¿Estás seguro?' }, remote:true %>
			</div>
			
		</div>
	<% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/_replace_comments_list.js.erb
$('#comments_list').replaceWith('<%= escape_javascript(render "comments/comments_list") %>');

app/views/comments/create.js.erb
<%= render 'tasks/update_history_list' %>

app/views/comments/destroy.js.erb
$('#comment_<%= @comment_id %>').fadeOut();

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>