config/routes.rb
######API#######
require 'api_constraints'

Rails.application.routes.draw do


  resources :colours

  get 'explorer/tree_view'
  get 'explorer/add_column'

  # API
  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do
      resources :projects do
        resources :tasks, only: [:index,:update,:show] do
          get 'all', on: :collection
          put 'update_gantt', on: :member, action:'update_gantt'
          delete 'update_gantt', on: :member, action:'destroy'
          post 'update_gantt', on: :collection, action:'create'
          resources :comments, only: [:create]
        end

        resources :indicators do
        end

        get 'all', on: :collection
      end

      #Métodos para usuarios
      post 'users/login', to: 'users#login'
      delete 'users/logout', to: 'users#logout'

      #Métodos de progresos
      get '/progress/estimated_in_resources_by_week' 
      get '/progress/real_in_resources_by_week' 
      get '/progress/estimated_in_days_by_week'
      get '/progress/real_in_days_by_week' 
      get '/progress/all_progress'

      get '/progress/performance_in_resources_by_week'
      get '/progress/performance_in_one_by_week'
      post '/push/send_token'

      
      get '/progress/performance_estimated_by_week'
      get '/progress/performance_real_by_week'

    end
  end

#######termino API#####
  
  # Página de errores
  get 'errors/file_not_found'
  get 'errors/unprocessable'
  get 'errors/internal_server_error'
  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all


  #usuarios con gema devise
  devise_for :users


  #Resources genera todas las rutas CRUD para cada uno de estos objetos
  resources :projects do
    get 'delete'
    get 'second_indicators'
    get 'tree_view'
    get 'root'
    get 'second_root'
    get 'stads'
    get 'add_tree_view_column'
    get 'export'
    get 'kanban_board', to: 'kanban_board#index', as: :kanban_board_index
    get 'gantt', to: 'gantt#index'

    resources :indicators
    resources :users, only: [:index]
    resources :tasks do
      resources :reports
      resources :comments

    end
  end

  resources :tasks do
    get 'delete_confirmation'
    get 'fast_report'
    get 'toggle_urgent'
    get 'change_colour'
    post 'move_dates'
  end
  get 'update_tree_view', to: 'tasks#update_tree_view'

  get 'gantt', to: 'gantt#index'
  get 'explorer', to: 'explorer#tree_view'

  resources :comments
  resources :reports
  resources :assignments
  resources :users

  resources :indicators

  resources :enterprises do
    resources :projects
    resources :users
  end

  namespace :kanban_board do
    get 'index'
    get 'update_item_partial'
  end




  root 'explorer#tree_view'
end

app/controllers/api/v1/projects_controller.rb
#Aquí definimos las respuestas a las llamadas de la api
module Api
  module V1
    class ProjectsController < ActionController::Base
      before_filter :restrict_access, only: [:index]
      before_action :set_user, only: [:index]
      #Con esto definimos como queremos entregar la respuesta.
      respond_to :json

      def index
        @projects = @user.projects
        respond_with @projects
      end

      def all
        @projects = User.find(current_user).projects
        render :file => "api/v1/projects/all.json.jbuilder",
               :content_type => 'application/json'
      end


      private
       def restrict_access
        token=request.headers["Authorization"]
        set_api_key(token)
        if @ak
          unless @ak.valid_token
            @ak.destroy
          end
        end
        unless ApiKey.exists?(access_token: token)
          render nothing: 'HTTP_ACCESS_DENIED', status: '403'
        end
      end

      def set_user
        token = request.headers["Authorization"]
        set_api_key(token)
        @user = @ak.user if @ak
      end

      def set_api_key(token)
        @ak = ApiKey.find_by_access_token(token)
      end
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  load_and_authorize_resource

  before_action :set_project, only: [:show, :edit, :update, :destroy, :stads]

  # GET /projects
  # GET /projects.json
  def index
    @projects = current_user.projects
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @users = @project.users
  end

  def second_indicators
    
  end

  # GET /projects/new
  def new
    @project = Project.new(owner_id: current_user.id)
  end

  # GET /projects/1/edit
  def edit
  end


  # POST /projects
  # POST /projects.json

  def create
    @project = Project.new(project_params)
    # a.a

    if params[:project][:xml_file]
      i = Importer.new(params[:project][:xml_file], user_id: current_user.id)
      i.import(@project)
    end

    respond_to do |format|
      if @project.save
        format.html { redirect_to explorer_tree_view_path }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # vista de confirmacion
  def delete
    @project = Project.find(params[:project_id])    
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    #cuando se borra un proyecto borrar también el archivo xml
    if @project.xml_file and File.exist?(@project.xml_file)
      File.delete(@project.xml_file)
    end
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  # metodo asociado a la vista de arbol de un proyecto y sus tareas
  def tree_view
    @project = Project.find(params[:project_id])

    respond_to do |format|
      format.html
      format.js
    end

  end

  # Metodo asociado a la vista de la carta gantt de un proyecto
  def gantt
    @project = Project.find(params[:project_id])
  end

  # Metodo asociado a la vista de indicadores de un proyecto
  def indicators
    @project = Project.find(params[:project_id])
  end

  def stads
    @users = @project.users
    @kanban = @project.kanban
  end

  def root
    # administrador
    if current_user.role_in_project(@project) == 1
      redirect_to explorer_tree_view_path(project_id: @project.id)
      
    # last_planer
    elsif current_user.role_in_project(@project) == 2
      redirect_to kanban_board_index_path(project_id: @project.id)
    end
  end

  def second_root
    # administrador
    if current_user.role_in_project(@project) == 1
      redirect_to project_stads_path(@project)
      
    # last_planer
    elsif current_user.role_in_project(@project) == 2
      redirect_to kanban_board_index_path(project_id: @project.id)
    end
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_project
    if params[:id]
      @project = Project.find(params[:id])
    elsif params[:project_id]
      @project = Project.find(params[:project_id])
    end
  end

  def check_permissions
    if !current_user.projects.include?(@project)
      redirect_to explorer_tree_view_path
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def project_params
    params.require(:project).permit(:name, :owner_id, :start_date, :end_date, :expected_start_date, :expected_end_date, :xml_file, :resources_type, :resources_reporting, :enterprise_id)
  end


end

app/helpers/projects_helper.rb
module ProjectsHelper

	def project_delta_progress_css(project, in_resources)
		if project.progress_delta(in_resources) < 0
			'bad'
		else
			'great'
		end
	end

	def project_delayed_days_progress_css(project, in_resources)
		if project.delayed_or_advanced_days(in_resources) < 0
			'bad'
		else
			'great'
		end
	end

	def css_project_status_color(project)
		if project.real_progress < project.expected_progress
			'bad'
		else
			'great'
		end
	end
end

app/views/projects/_days_indicators.html.erb
<div class="row">
	<div class="chart" id="days_chart" class="col-md-12">

	</div>
</div>
<div class="row">

	<div class="col-md-3 indicator-footer" id="real_progress">
		<div class="row">
			<div class="col-md-12">
				Avance
			</div>
			<div class="col-md-12">
				<%= @project.real_progress %> %
			</div>
		</div>
	</div>

	<div class="col-md-3 indicator-footer <%= project_delta_progress_css(@project, false) %>">
		<div class="row">
			<div class="col-md-12">
				Diferencia
			</div>
			<div class="col-md-12">
				<%= @project.progress_delta(false) %> %
			</div>
		</div>
	</div>

	<div class="col-md-3 indicator-footer" id="expected_progress">
		<div class="row">
			<div class="col-md-12">
				Avance esperado
			</div>
			<div class="col-md-12">
				<%= @project.expected_progress %> %
			</div>
		</div>
	</div>

	<div class="col-md-3 indicator-footer <%= project_delayed_days_progress_css(@project, false) %>">
		<div class="row">
			<div class="col-md-12">
				<%= @project.f_delayed_or_advanced_days(false)[0] %>
			</div>
			<div class="col-md-12">
				<%= @project.f_delayed_or_advanced_days(false)[1] %>
			</div>
		</div>
	</div>
</div>

app/views/projects/_edit_form.html.erb
<%= bootstrap_form_for(@project) do |f| %>

  <!-- NOMBRE -->
  <%= f.text_field :name, :required => true, :label => 'Nombre *' %>

  <%= f.form_group do %>
    <!-- OWNER -->
    <%= f.submit "Terminar edición" %>
  <% end %>

<% end %>
 

app/views/projects/_form.html.erb
<%= bootstrap_form_for(@project) do |f| %>

  <!-- NOMBRE -->
  <%= f.text_field :name, :required => true, :label => 'Nombre *' %>

  <!-- FECHA DE INICIO -->
   <!-- f.date_select :expected_start_date, {:use_month_names => ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre','Diciembre']}, :required => true, :label => 'Fecha de Inicio' %> -->

  <!-- FECHA DE TERMINO -->
   <!-- f.date_select :expected_end_date, {:use_month_names => ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre','Diciembre']}, :required => true, :label => 'Fecha de Término' %> -->

  <!-- TIPO DE RECURSOS     -->
  <%= f.select :resources_type, [['Seleccionar', ''],['Sin recursos, solo tiempo', 0], ['Dolares', 1], ['UF', 2], ['Horas Hombres', 3]], :label => 'Tipo de Recursos *', required: true %>

  <!-- REPORTAR AVANCES EN TIEMPO REAL -->
  <!-- f.select :resources_reporting, [['Seleccionar', false], ['Quiero reportar en tiempo real el uso de recursos', true], ['No quiero reportar en tiempo real el uso de recursos', false]], :label => 'Reportar Recursos' %> -->

  <!-- IMPORTACIÓN -->
  <!-- f.file_field :xml_file , :label => 'Importar (Opcional)', :accept =>'text/xml' -->

  <!-- EMPRESA -->
  <!-- f.hidden_field :enterprise_id, value: @enterprise.id  -->
    <%= f.hidden_field :owner_id, value: @project.owner_id %>

  <%= f.form_group do %>
    <!-- OWNER -->
  <%= f.submit "Crear Proyecto" %>
  <% end %>

<% end %>
 

app/views/projects/_gant_tree_view_sub_menu.html.erb
<div class="full horizontal_sub_menu">
	<table>
		<tr>
			<td class="<%= 'active' if params[:action] == 'gantt' %>"><%= link_to 'Gantt', project_gantt_path(@project)%></td>
			<td class="<%= 'active' if params[:action] == 'tree_view' %>"><%= link_to 'Explorador', project_tree_view_path(@project)%></td>
		</tr>
	</table>
</div>

app/views/projects/_resources_indicators.html.erb
<div class="row">
	<div id="resources_chart">

	</div>
</div>

<div class="row">
	<div class="col-md-3 indicator-footer" id="real_progress">
		<div class="row">
			<div class="col-md-12">
				Avance
			</div>
			<div class="col-md-12">
				<%= @project.real_progress %> %
			</div>
		</div>
	</div>

	<div class="col-md-3 indicator-footer <%= project_delta_progress_css(@project, false) %>">
		<div class="row">
			<div class="col-md-12">
				Diferencia
			</div>
			<div class="col-md-12">
				<%= @project.progress_delta(true) %> %
			</div>
		</div>
	</div>

	<div class="col-md-3 indicator-footer" id="expected_progress">
		<div class="row">
			<div class="col-md-12">
				Avance esperado
			</div>
			<div class="col-md-12">
				<%= @project.expected_progress %> %
			</div>
		</div>
	</div>

	<div class="col-md-3 indicator-footer <%= project_delayed_days_progress_css(@project, false) %>">
		<div class="row">
			<div class="col-md-12">
				<%= @project.f_delayed_or_advanced_days(true)[0] %>
			</div>
			<div class="col-md-12">
				<%= @project.f_delayed_or_advanced_days(true)[1] %>
			</div>
		</div>
	</div>
</div>

app/views/projects/_users.html.erb
<div class="col-md-6">
  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th class="col-lg-5" colspan="2">Usuarios</th>
        </tr>
      </thead>
      <tbody>
      <% @project.users.each do |u| %>
        <tr>
          <td><%= u.name %></td>
          <td><%= u.role_u %></td>          
        </tr>
      <% end %>
      </tbody>
    </table>      
  </div>
</div>

app/views/projects/add_tree_view_column.js.erb
	$(function(){

	//Removemos todas las columnas despues de la clickeada
	$('#column_<%= @task.parent_id ? @task.parent_id : 0 %>').nextAll().remove();

	// Removemos el atributo active de class de todos los items de la columna clickeada
	$('#column_<%= @task.parent_id ? @task.parent_id : 0 %>').find('.item .arrow').removeClass('active');

	//Al item clickeado lo dejamos active
	$('#task_item_<%= @task.id %> .arrow').addClass('active');
	$('#project_item_<%= @task.project_id %> .arrow').addClass('active');

	//Agregamos el partial column a tree view via append, escape_javascript
	$('#tree_view_content').append('<%= escape_javascript(render "projects/explorer/tree_view_column", parent: @task) %>');

	// Nos movemos hacia el final de la div tree view para ver completa la columna recien agregada
	$('#tree_view').animate( { scrollLeft: '+=500' }, 500, 'easeOutQuad' );
});

app/views/projects/edit.html.erb
<div class="row modal-header">
	<div clas="col-md-12">
		<table>
			<tr>
				<td><span class="glyphicon glyphicon-edit"></span></td>
				<td>Editar proyecto <%= @project.name %></td>
			</tr>
		</table>
	</div>
</div>

<div class="row">
	<div class="col-md-12 little-form">
		<h2>Datos a editar</h2>
		<%= render 'edit_form' %>
	</div>
</div>

app/views/projects/index.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Proyectos</h1>
  </div>
</div>


<div class="row">
  <div class="col-md-12">
    <table class="table">
      <thead>
        <tr>
          <th>Nombre</th>
          <th>Unidad</th>
          <th>Avance</th>
          <th>Avance esperado</th>
          <th>Inicio esperado</th>
          <th>Término esperado</th>
          <th>Ultimo reporte</th>
          <th>Rol</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @projects.each do |p| %>
          <tr>
            <td><%= link_to p.name, project_root_path(p) %></td> 
            <td><%= p.f_resources_type %></td> 
            <td><%= p.progress.to_f %> %</td>
            <td><%= p.expected_progress.to_f %> %</td>
            <td><%= f_date(p.expected_start_date) %></td>
            <td><%= f_date(p.expected_end_date) %></td>
            <% if p.last_report %>
              <td><%= f_date(p.last_report.created_at) %> <br> <%= p.last_report.user ? p.last_report.user.f_name : 'Importación' %></td>
            <% else %>
              <td></td>
            <% end %>
            <td><%= current_user.f_role_in_project(p)%></td>
            <td><%= link_to 'detalles', p %></td>
            <% if p.owner == current_user %>
              <td><%= link_to_modal 'X', project_delete_path(p) %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>


<div class="row">
  <div class="col-md-12">
    <%= link_to_modal 'Nuevo proyecto', new_project_path(@enterprise) %>
  </div>
</div>

app/views/projects/indicators.html.erb
<%= render 'indicators/show'%>

app/views/projects/second_indicators.html.erb
<div class="row">
	<div class="col-md-12">
		<h1>Indicadores</h1>
	</div>
</div>
<div class="row">
	<div class="col-md-12" id="indicators">
		<% if @project.resources_type != 0 %>
			<%= render 'resources_indicators' %>
		<% else %>
			<%= render 'days_indicators' %>
		<% end %>

		<% if @project.resources_reporting %>
			<%= render 'performance_indicators' %>
		<% end %>
	</div>
</div>

app/views/projects/show.html.erb
<!-- nombre del proyecto -->
<div class="row">
  <div class="col-md-12">
    <h1><%= @project.name %></h1>
  </div>
</div>


<!-- listado de usuarios -->
<div class="row">
	<div class="col-md-12 pro_container">
		<div class="container">
			<div class="title">
				<span class="glyphicon glyphicon-user"></span>
				Usuarios
			</div>
			
		  	<table class="table pro">
		  		<thead>
		  			<th>Nombre</th>
		  			<th>Rol</th>
		  			<th>N° de reportes</th>
		  			<th></th>
		  			<th></th>
		  		</thead>
			    <% @users.each do |u| %>
			    	<tr>
			    		<td><%= u.f_name %></td>
			    		<td><%= u.f_role_in_project(@project) %></td>
			    		<td><%= u.reports_in_project(@project).count %></td>
			    		<td><%= link_to 'Detalles', assignment_path(u.assignment_in_project(@project).id) %></td>
		    			<td>
				    		<% if !u.super_admin && (@project.owner == current_user || current_user.super_admin) %>
				    			<%= link_to_modal 'Editar asignación', edit_assignment_path(u.assignment_in_project(@project).id) %>
				    		<% end %>
		    			</td>
			    	</tr>
			    <% end %>
		  	</table>
		</div>
	</div>
</div>

<!-- agregar usuario y editar proyecto -->
<% if @project.owner == current_user %>
	<div class="row">
		<div class="col-md-12">
			<%= link_to_modal 'Agregar usuario', new_assignment_path(project_id: @project.id) %>
		</div>
	</div>


	<div class="row">
		<div class="col-md-12">
			<%= link_to_modal 'Editar proyecto', edit_project_path(@project) %>
		</div>
	</div>
<% end %>

app/views/projects/stads.html.erb
<!-- titulo -->
<div class="row">
	<div class="col-md-12">
		<h1>Estadisticas</h1>
	</div>
</div>

<!-- MENU tabs -->
<div class="row pro_tabs option_group">
	<div class="col-md-12">
		<table>
			<tr>
				<td class="option active" id="tab_1">Graficos de avance</td>
				<td class="option" id="tab_2">Tareas</td>
			</tr>
		</table>
	</div>
</div>


<!-- INDICADORES -->
<div class="row content_tab" id="content_tab_1">
	<div class="col-md-12 pro_container">
		<div class="container">
			<div class="title">
				<span class="glyphicon glyphicon-list-alt"></span>
				Indicadores
			</div>
			<div class="row" id="indicators">
				<% if @project.resources_type != 0 %>
					<%= render 'resources_indicators' %>
				<% else %>
					<%= render 'days_indicators' %>
				<% end %>

				<% if @project.resources_reporting %>
					<%= render 'performance_indicators' %>
				<% end %>
			</div>
		</div>

	</div>
</div>


<!-- ASIGNACIONES -->
<%= render 'projects/stads/tasks' %>

app/views/projects/tree_view.html.erb
<div id="tree_view">
	<!-- Header de la vista explorador (tree_view) 	 -->
	<%= render 'projects/explorer/tree_view_header'%>
	
	<div class="full" id="tree_view_content">
		<!-- Se crea una columna inicial que corresponde a las tareas de primer nivel -->
		<%= render 'projects/explorer/tree_view_column', parent: @project %>
	</div>
</div>