config/routes.rb
######API#######
require 'api_constraints'

Rails.application.routes.draw do


  resources :colours

  get 'explorer/tree_view'
  get 'explorer/add_column'

  # API
  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do
      resources :projects do
        resources :tasks, only: [:index,:update,:show] do
          get 'all', on: :collection
          put 'update_gantt', on: :member, action:'update_gantt'
          delete 'update_gantt', on: :member, action:'destroy'
          post 'update_gantt', on: :collection, action:'create'
          resources :comments, only: [:create]
        end

        resources :indicators do
        end

        get 'all', on: :collection
      end

      #Métodos para usuarios
      post 'users/login', to: 'users#login'
      delete 'users/logout', to: 'users#logout'

      #Métodos de progresos
      get '/progress/estimated_in_resources_by_week' 
      get '/progress/real_in_resources_by_week' 
      get '/progress/estimated_in_days_by_week'
      get '/progress/real_in_days_by_week' 
      get '/progress/all_progress'

      get '/progress/performance_in_resources_by_week'
      get '/progress/performance_in_one_by_week'
      post '/push/send_token'

      
      get '/progress/performance_estimated_by_week'
      get '/progress/performance_real_by_week'

    end
  end

#######termino API#####
  
  # Página de errores
  get 'errors/file_not_found'
  get 'errors/unprocessable'
  get 'errors/internal_server_error'
  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all


  #usuarios con gema devise
  devise_for :users


  #Resources genera todas las rutas CRUD para cada uno de estos objetos
  resources :projects do
    get 'delete'
    get 'second_indicators'
    get 'tree_view'
    get 'root'
    get 'second_root'
    get 'stads'
    get 'add_tree_view_column'
    get 'export'
    get 'kanban_board', to: 'kanban_board#index', as: :kanban_board_index
    get 'gantt', to: 'gantt#index'

    resources :indicators
    resources :users, only: [:index]
    resources :tasks do
      resources :reports
      resources :comments

    end
  end

  resources :tasks do
    get 'delete_confirmation'
    get 'fast_report'
    get 'toggle_urgent'
    get 'change_colour'
    post 'move_dates'
  end
  get 'update_tree_view', to: 'tasks#update_tree_view'

  get 'gantt', to: 'gantt#index'
  get 'explorer', to: 'explorer#tree_view'

  resources :comments
  resources :reports
  resources :assignments
  resources :users

  resources :indicators

  resources :enterprises do
    resources :projects
    resources :users
  end

  namespace :kanban_board do
    get 'index'
    get 'update_item_partial'
  end




  root 'explorer#tree_view'
end

app/models/report.rb
class Report < ActiveRecord::Base
	belongs_to :task
	belongs_to :user
	after_destroy :update_project_indicators
	after_create :update_project_indicator
	before_save :update_task

	def project
		task.project
	end

	def user_f_name
		if user
			user.f_name
		else
			'Importacion'
		end
	end

	# actualizamos todos los indicadores del proyecto
	def update_project_indicators
		# que se actualicen los indicadores del proyect solo cuando fue eliminado manualmente
		if !@destroyed_by_association
			project.manage_indicators
		end
	end

	# actualizamos solo un indicador del proyecto
	def update_project_indicator
		# que se actualicen los indicadores del proyect solo cuando fue eliminado manualmente
		if !@destroyed_by_association
			project.manage_indicator(self)
		end
	end

	def update_task
		if task_id
			self.task.refresh
		end
	end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new(user_id: params[:user_id], progress: params[:progress], task_id: params[:task_id])
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)
    @project = @report.project
    @task = @report.task

    respond_to do |format|
      if @report.save
        format.html { redirect_to request.referer }
        format.json { render :show, status: :created, location: @report }
        format.js 
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update

    respond_to do |format|
      if @report.update(report_params)
        @report.update_project_indicator(@report)
        format.html { redirect_to request.referer }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @project = @report.project
    @task = @report.task
    @report_id = @report.id
    @report.destroy

    # refrescamos la tarea
    @task.refresh
    respond_to do |format|
      format.html { redirect_to request.referer }
      format.json { head :no_content }
      format.js 
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_report
    @report = Report.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def report_params
    params.require(:report).permit(:task_id, :progress, :user_id)
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_destroy.js.erb
<%= render 'explorer/update_tree_view.js.erb' %>
<%= render 'tasks/update_history_list' %>
<%= render 'kanban_board/update_item_partial' %>

app/views/reports/_form.html.erb
<%= bootstrap_form_for(@report) do |f| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% @report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :task_id %>
  <%= f.hidden_field :user_id %>
  <%= f.hidden_field :progress %>

  <% if @report.task.project.resources_reporting %>
    <%= f.number_field :resources, label:'Recursos utilizados' %>    
  <% end %>

  <%= f.submit %>
<% end %>

app/views/reports/create.js.erb
<%= render 'create.js.erb' %>

app/views/reports/destroy.js.erb
<%= render 'destroy.js.erb' %>

app/views/reports/edit.html.erb
<h1>Editando Reporte</h1>

<%= render 'form' %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<h1>Listing reports</h1>


<table>
  <thead>
    <tr>
      <th>Id task</th>
      <th>Progress</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.id_task %></td>
        <td><%= report.progress %></td>
        <td><%= report.date %></td>
        <td><%= link_to 'Show', report %></td>
        <td><%= link_to 'Edit', edit_report_path(report) %></td>
        <td><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Report', new_report_path %>

app/views/reports/new.html.erb
<h1>Nuevo reporte para <%= @report.task.name %></h1>

<%= render 'form' %>

app/views/reports/show.html.erb
<p>
  <strong>Id task:</strong>
  <%= @report.id_task %>
</p>

<p>
  <strong>Progress:</strong>
  <%= @report.progress %>
</p>

<p>
  <strong>Date:</strong>
  <%= @report.date %>
</p>

<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>